import { Chess, Move } from "chess.js";
import { inject, Lifecycle, scoped } from "tsyringe";

import { AiRegisterOptions, REGISTER_OPTIONS_TOKEN } from "../../shared";
import { BasicBotService } from "../basic-bot/basic-bot.service";

/**
 * @description Generated by cursor.
 * @author Cursor Composer
 * @co-author @Neosoulink (https://github.com/Neosoulink)
 * @version 2
 */
@scoped(Lifecycle.ContainerScoped)
export class StockfishService {
	constructor(
		@inject(Chess) private readonly game: Chess,
		@inject(BasicBotService) private readonly basicBot: BasicBotService,
		@inject(REGISTER_OPTIONS_TOKEN)
		private readonly options: AiRegisterOptions | undefined
	) {}

	async getMove(): Promise<Move | null> {
		const legal = this.game.moves({ verbose: true });
		if (legal.length === 0) return null;

		try {
			const base = this.options?.proxyBaseUrl?.replace(/\/$/, "");
			if (!base)
				throw new Error(
					"Requires AiRegisterOptions.proxyBaseUrl (chess server)."
				);

			const fen = this.game.fen();
			const url = `${base}/ai/stockfish/best-move`;
			let res: Response;
			try {
				res = await fetch(url, {
					method: "POST",
					headers: { "Content-Type": "application/json" },
					body: JSON.stringify({ fen, moveTimeMs: 400 }),
					mode: "cors"
				});
			} catch (e) {
				throw new Error(
					"Proxy request failed:" +
						url +
						" " +
						(e instanceof Error ? e.message : String(e))
				);
			}

			if (!res.ok)
				throw new Error("Proxy error:" + res.status + " " + (await res.text()));

			const data = (await res.json()) as { uci?: string };
			const uci = data.uci ?? "";
			const found = legal.find(
				(m) => m.from + m.to + (m.promotion ?? "") === uci
			);

			if (found) return found;
			throw new Error("UCI did not match a legal move:" + uci);
		} catch (error) {
			console.warn(
				`[chess-d/ai]: ${StockfishService.name} failed to get move:`,
				error instanceof Error ? error.message : String(error)
			);
			return this.basicBot.findBestMove();
		}
	}
}
