export const ENGINE_PIECE_SELECTED_TOKEN = "ENGINE_PIECE_SELECTED";
export const ENGINE_WILL_UNDO_TOKEN = "ENGINE_WILL_UNDO";
export const ENGINE_WILL_REDO_TOKEN = "ENGINE_WILL_REDO";
export const ENGINE_WILL_GO_TO_MOVE_TOKEN = "ENGINE_WILL_GO_TO_MOVE";
