import { SupportedAiProvider } from "@chess-d/shared";
import { inject, Lifecycle, scoped } from "tsyringe";
import { Chess, Move } from "chess.js";

import { AiRegisterOptions, REGISTER_OPTIONS_TOKEN } from "../../shared";
import { BasicBotService } from "../basic-bot/basic-bot.service";

type LlmProvider = "openai" | "gemini" | "anthropic";

/**
 * @description Generated by cursor.
 * @author Cursor Composer
 * @co-author @Neosoulink (https://github.com/Neosoulink)
 * @version 2
 */
@scoped(Lifecycle.ContainerScoped)
export class LlmService {
	constructor(
		@inject(Chess) private readonly game: Chess,
		@inject(BasicBotService) private readonly basicBot: BasicBotService,
		@inject(REGISTER_OPTIONS_TOKEN)
		private readonly options: AiRegisterOptions | undefined
	) {}

	private _matchUci(text: string, legal: Move[]): Move | null {
		const lower = text.toLowerCase();
		const uciRe = /\b([a-h][1-8][a-h][1-8][qrnb]?)\b/;
		const m = lower.match(uciRe);
		if (!m?.[1]) return null;
		const uci = m[1];
		const found = legal.find(
			(v) => v.from + v.to + (v.promotion ?? "") === uci
		);
		return found ?? null;
	}

	private _fallbackMove(): Move | null {
		return this.basicBot.findBestMove();
	}

	private async _pickMoveFromText(
		rawText: string,
		legal: Move[]
	): Promise<Move | null> {
		const fromUci = this._matchUci(rawText, legal);
		if (fromUci) return fromUci;

		const lines = rawText.split(/\r?\n/).map((l) => l.trim());
		for (const line of lines) {
			const fromLine = this._matchUci(line, legal);
			if (fromLine) return fromLine;
		}

		for (const token of rawText.split(/\s+/)) {
			const clean = token.replace(/[^a-z0-9+#=-]/gi, "");
			if (!clean) continue;
			const trial = new Chess(this.game.fen());
			const attempt = trial.move(clean);
			if (attempt) {
				const match = legal.find(
					(m) =>
						m.from === attempt.from &&
						m.to === attempt.to &&
						(m.promotion ?? "") === (attempt.promotion ?? "")
				);
				if (match) return match;
			}
		}

		console.warn(
			"[chess-d/ai] LLM reply did not map to a legal move; using basic bot."
		);
		return this._fallbackMove();
	}

	public async getProviderMove(
		provider: SupportedAiProvider
	): Promise<Move | null> {
		const legalMoves = this.game.moves({ verbose: true });
		if (legalMoves.length === 0) return null;

		const base = this.options?.proxyBaseUrl?.replace(/\/$/, "");
		if (!base) {
			console.warn(
				`[chess-d/ai] ${provider} requires the chess API server (AiRegisterOptions.proxy.baseUrl). Falling back to basic bot.`
			);
			return this._fallbackMove();
		}

		const fen = this.game.fen();
		const legalUci = legalMoves.map((m) => m.from + m.to + (m.promotion ?? ""));
		const url = `${base}/ai/llm/move`;

		let res: Response;
		try {
			res = await fetch(url, {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({
					provider,
					fen,
					legalUci
				}),
				mode: "cors"
			});
		} catch (e) {
			console.warn(
				`[chess-d/ai] LLM proxy request failed (${provider}, ${url}). Check server + CORS (CLIENT_HOST vs page origin).`,
				e
			);
			return this._fallbackMove();
		}

		if (!res.ok) {
			console.warn(
				`[chess-d/ai] LLM proxy error (${provider}):`,
				res.status,
				await res.text()
			);
			return this._fallbackMove();
		}

		const data = (await res.json()) as { text?: string };
		const text = data.text ?? "";
		return this._pickMoveFromText(text, legalMoves);
	}
}
