export const SOCKET_ROOM_CREATED_TOKEN = "SOCKET_ROOM_CREATED";
export const SOCKET_JOINED_ROOM_TOKEN = "SOCKET_JOINED_ROOM";
export const SOCKET_LEFT_ROOM_TOKEN = "SOCKET_LEFT_ROOM";
export const SOCKET_MOVE_PERFORMED_TOKEN = "SOCKET_MOVE_PERFORMED";
