export const SOCKET_ROOM_CREATED_TOKEN = "SOCKET_ROOM_CREATED";
export const SOCKET_JOINED_ROOM_TOKEN = "SOCKET_JOINED_ROOM";
export const SOCKET_PERFORM_MOVE_TOKEN = "SOCKET_PERFORM_MOVE";
export const SOCKET_MOVE_PERFORMED_TOKEN = "SOCKET_MOVE_PERFORMED";
