import { URL as nodeUrl } from "node:url";
import * as nodeHttp from "node:http";
import * as nodeHttps from "node:https";
import {
	BadRequestException,
	Injectable,
	ServiceUnavailableException
} from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import { SupportedAiProvider } from "@chess-d/shared";

const OPENAI_DEFAULT_BASE = "https://api.openai.com/v1";

/**
 * @description Generated by cursor.
 * @author Cursor Composer
 * @co-author @Neosoulink (https://github.com/Neosoulink)
 * @version 2
 */
@Injectable()
export class LlmProxyService {
	constructor(private readonly config: ConfigService) {}

	/** @description POST JSON without relying on global `fetch`. */
	private _postJson(
		urlStr: string,
		headers: Record<string, string>,
		body: unknown
	): Promise<{
		ok: boolean;
		status: number;
		text(): Promise<string>;
		json(): Promise<unknown>;
	}> {
		const payload = JSON.stringify(body);
		const url = new nodeUrl(urlStr);
		const isHttps = url.protocol === "https:";
		const lib = isHttps ? nodeHttps : nodeHttp;
		const defaultPort = isHttps ? 443 : 80;

		return new Promise((resolve, reject) => {
			const req = lib.request(
				{
					hostname: url.hostname,
					port: url.port || defaultPort,
					path: url.pathname + url.search,
					method: "POST",
					headers: {
						...headers,
						"Content-Length": Buffer.byteLength(payload, "utf8")
					}
				},
				(res) => {
					const chunks: Buffer[] = [];
					res.on("data", (c: Buffer) => chunks.push(c));
					res.on("end", () => {
						const raw = Buffer.concat(chunks).toString("utf8");
						const status = res.statusCode ?? 0;
						resolve({
							ok: status >= 200 && status < 300,
							status,
							text: async () => raw,
							json: async () => JSON.parse(raw) as unknown
						});
					});
				}
			);
			req.on("error", reject);
			req.write(payload, "utf8");
			req.end();
		});
	}

	public async completeMove(
		provider: SupportedAiProvider,
		fen: string,
		legalUci: string[],
		model?: string
	): Promise<string> {
		const promptUser = `FEN: ${fen}\nLegal UCI moves: ${legalUci.join(", ")}\nReply with exactly one legal UCI move, nothing else.`;

		if (provider === SupportedAiProvider.openai) {
			const apiKey = this.config.get<string>("OPENAI_API_KEY");
			if (!apiKey)
				throw new ServiceUnavailableException(
					"OPENAI_API_KEY is not configured."
				);
			const base = (
				this.config.get<string>("OPENAI_BASE_URL") ?? OPENAI_DEFAULT_BASE
			).replace(/\/$/, "");
			const m =
				model ?? this.config.get<string>("OPENAI_MODEL") ?? "gpt-4o-mini";
			const res = await this._postJson(
				`${base}/chat/completions`,
				{
					Authorization: `Bearer ${apiKey}`,
					"Content-Type": "application/json"
				},
				{
					model: m,
					temperature: 0.2,
					messages: [
						{
							role: "system",
							content:
								"You are a chess engine. Reply with exactly one legal move in UCI format only."
						},
						{ role: "user", content: promptUser }
					]
				}
			);

			if (!res.ok)
				throw new BadRequestException(
					`OpenAI error: ${res.status} ${await res.text()}`
				);

			const data = (await res.json()) as {
				choices?: { message?: { content?: string } }[];
			};
			return data.choices?.[0]?.message?.content?.trim() ?? "";
		}

		if (provider === SupportedAiProvider.gemini) {
			const apiKey = this.config.get<string>("GEMINI_API_KEY");
			if (!apiKey)
				throw new ServiceUnavailableException(
					"GEMINI_API_KEY is not configured."
				);
			const m =
				model ?? this.config.get<string>("GEMINI_MODEL") ?? "gemini-2.0-flash";
			const url = `https://generativelanguage.googleapis.com/v1beta/models/${m}:generateContent?key=${encodeURIComponent(apiKey)}`;
			const res = await this._postJson(
				url,
				{ "Content-Type": "application/json" },
				{
					contents: [
						{
							parts: [
								{
									text: `You are a chess engine. UCI only.\n${promptUser}`
								}
							]
						}
					],
					generationConfig: { temperature: 0.2 }
				}
			);

			if (!res.ok)
				throw new BadRequestException(
					`Gemini error: ${res.status} ${await res.text()}`
				);
			const data = (await res.json()) as {
				candidates?: { content?: { parts?: { text?: string }[] } }[];
			};
			return data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ?? "";
		}

		if (provider === SupportedAiProvider.anthropic) {
			const apiKey = this.config.get<string>("ANTHROPIC_API_KEY");
			if (!apiKey)
				throw new ServiceUnavailableException(
					"ANTHROPIC_API_KEY is not configured."
				);
			const m =
				model ??
				this.config.get<string>("ANTHROPIC_MODEL") ??
				"claude-3-5-sonnet-20241022";

			const res = await this._postJson(
				"https://api.anthropic.com/v1/messages",
				{
					"Content-Type": "application/json",
					"x-api-key": apiKey,
					"anthropic-version": "2023-06-01"
				},
				{
					model: m,
					max_tokens: 64,
					messages: [
						{ role: "user", content: `Chess UCI only.\n${promptUser}` }
					]
				}
			);

			if (!res.ok)
				throw new BadRequestException(
					`Anthropic error: ${res.status} ${await res.text()}`
				);

			const data = (await res.json()) as {
				content?: { text?: string }[];
			};
			return data.content?.[0]?.text?.trim() ?? "";
		}

		throw new BadRequestException(`Unknown LLM provider: ${String(provider)}`);
	}
}
