import {
	Injectable,
	Logger,
	OnModuleDestroy,
	ServiceUnavailableException
} from "@nestjs/common";

type StockfishEngine = {
	sendCommand(cmd: string): void;
	listener?: (line: string) => void;
};

const initStockfish: (
	pathOrCb?: string | ((err: Error | null, engine?: StockfishEngine) => void)
) => Promise<StockfishEngine> = require("stockfish");

/**
 * @description Generated by cursor.
 * @author Cursor Composer
 * @co-author @Neosoulink (https://github.com/Neosoulink)
 * @version 2
 */
@Injectable()
export class StockfishEngineService implements OnModuleDestroy {
	private readonly logger = new Logger(StockfishEngineService.name);
	private engine: StockfishEngine | null = null;
	private bootPromise: Promise<void> | null = null;
	/** Set when init fails — surfaced on `/ai/chess/health` and in logs. */
	lastBootError: string | null = null;
	private searchResolver: {
		resolve: (uci: string) => void;
		reject: (e: Error) => void;
	} | null = null;

	constructor() {
		this.bootPromise = this.boot();
	}

	/** True after UCI handshake succeeded. */
	get engineReady(): boolean {
		return this.engine !== null;
	}

	private handleEngineLine = (line: string): void => {
		if (!this.searchResolver) return;
		const trimmed = line.trim();
		const bm = trimmed.match(/^bestmove (\S+)/);
		if (!bm) return;
		const uci = bm[1];
		const { resolve, reject } = this.searchResolver;
		this.searchResolver = null;
		if (uci === "(none)") reject(new Error("Stockfish: no legal move"));
		else resolve(uci);
	};

	/**
	 * Full multi-threaded WASM often fails in Node without thread flags.
	 * Prefer single-threaded / lite builds (see stockfish.js keywords).
	 */
	private async createEngine(): Promise<StockfishEngine> {
		const variants: (string | null)[] = ["single", "lite-single", "lite", null];
		let last: unknown;
		for (const v of variants) {
			try {
				const label = v ?? "default";
				this.logger.log(`Trying Stockfish engine variant: ${label}`);
				const eng = v ? await initStockfish(v) : await initStockfish();
				return eng;
			} catch (e) {
				last = e;
				this.logger.warn(
					`Stockfish variant ${v ?? "default"} failed: ${e instanceof Error ? e.message : e}`
				);
			}
		}
		throw last instanceof Error
			? last
			: new Error(String(last ?? "Stockfish init failed"));
	}

	private feedHandshakeLines(
		lines: string[],
		state: { sawUciOk: boolean },
		eng: StockfishEngine,
		resolve: () => void,
		reject: (e: Error) => void,
		timeout: ReturnType<typeof setTimeout>
	): void {
		for (const raw of lines) {
			const line = raw.trim();
			if (!line) continue;
			if (!state.sawUciOk && line.includes("uciok")) {
				state.sawUciOk = true;
				eng.sendCommand("isready");
				continue;
			}
			if (state.sawUciOk && line.includes("readyok")) {
				clearTimeout(timeout);
				eng.listener = this.handleEngineLine;
				resolve();
				return;
			}
		}
	}

	private async boot(): Promise<void> {
		try {
			const eng = await this.createEngine();
			this.engine = eng;
			await new Promise<void>((resolve, reject) => {
				const state = { sawUciOk: false };
				const timeout = setTimeout(
					() => reject(new Error("Stockfish UCI handshake timeout")),
					20000
				);
				eng.listener = (chunk: string) => {
					const lines = String(chunk).split(/\r?\n/);
					this.feedHandshakeLines(lines, state, eng, resolve, reject, timeout);
				};
				eng.sendCommand("uci");
			});
			this.lastBootError = null;
			this.logger.log("Stockfish UCI ready.");
		} catch (e) {
			const msg = e instanceof Error ? e.message : String(e);
			this.lastBootError = msg;
			this.logger.error(
				`Failed to initialize Stockfish (${msg}). Tried single / lite-single / lite / default.
				\nEnsure Stockfish WASM bundle was installed.`,
				e
			);
			this.engine = null;
		}
	}

	async getBestMoveUci(fen: string, moveTimeMs = 400): Promise<string> {
		await this.bootPromise;
		if (!this.engine) {
			throw new ServiceUnavailableException(
				this.lastBootError
					? `Stockfish engine is not available: ${this.lastBootError}`
					: "Stockfish engine is not available on this server."
			);
		}
		if (this.searchResolver) {
			throw new ServiceUnavailableException(
				"Stockfish is busy; try again in a moment."
			);
		}
		const mt = Math.min(60000, Math.max(50, moveTimeMs));
		return new Promise((resolve, reject) => {
			const to = setTimeout(() => {
				if (this.searchResolver) {
					this.searchResolver = null;
					reject(new Error("Stockfish search timeout"));
				}
			}, mt + 8000);
			this.searchResolver = {
				resolve: (uci) => {
					clearTimeout(to);
					resolve(uci);
				},
				reject: (e) => {
					clearTimeout(to);
					reject(e);
				}
			};
			this.engine!.sendCommand("stop");
			this.engine!.sendCommand("ucinewgame");
			this.engine!.sendCommand(`position fen ${fen}`);
			this.engine!.sendCommand(`go movetime ${mt}`);
		});
	}

	onModuleDestroy(): void {
		try {
			this.engine?.sendCommand("quit");
		} catch {
			// ignore
		}
	}
}
